import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import JSZip from "jszip";

const skin_dir = path.resolve(process.cwd(), "src/assets/default-skin");
const embedded_module_path = path.resolve(process.cwd(), "src/assets/default_skin_embedded.ts");

const collect_files = async (dir: string, base_dir: string): Promise<string[]> => {
    const entries = await readdir(dir, { withFileTypes: true });
    const files: string[] = [];

    for (const entry of entries) {
        const absolute = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            files.push(...(await collect_files(absolute, base_dir)));
            continue;
        }

        const relative = path.relative(base_dir, absolute).split(path.sep).join("/");
        if (relative === "manifest.json") {
            continue;
        }
        files.push(relative);
    }

    return files;
};

const main = async (): Promise<void> => {
    const files = await collect_files(skin_dir, skin_dir);
    files.sort((a, b) => a.localeCompare(b));

    const zip = new JSZip();
    for (let i = 0; i < files.length; i++) {
        const relative = files[i];
        const absolute = path.join(skin_dir, relative);
        const content = await readFile(absolute);
        zip.file(relative, content);
    }

    const archive = await zip.generateAsync({
        type: "uint8array",
        compression: "DEFLATE",
        compressionOptions: { level: 9 }
    });
    const archive_base64 = Buffer.from(archive).toString("base64");

    const module = `// generated by scripts/generate_skin.ts
import JSZip from "jszip";

const DEFAULT_SKIN_ARCHIVE_BASE64 = ${JSON.stringify(archive_base64)};

let cached_default_skin_files: Map<string, ArrayBuffer> | null = null;
let loading_default_skin_files: Promise<Map<string, ArrayBuffer>> | null = null;

const decode_base64_to_array_buffer = (value: string): ArrayBuffer => {
    const binary = atob(value);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) {
        bytes[i] = binary.charCodeAt(i);
    }
    return bytes.buffer;
};

export const get_default_skin_embedded_files = async (): Promise<Map<string, ArrayBuffer>> => {
    if (cached_default_skin_files) {
        return cached_default_skin_files;
    }

    if (loading_default_skin_files) {
        return loading_default_skin_files;
    }

    loading_default_skin_files = (async () => {
        const archive = decode_base64_to_array_buffer(DEFAULT_SKIN_ARCHIVE_BASE64);
        const zip = await JSZip.loadAsync(archive);
        const files = new Map<string, ArrayBuffer>();
        const entries = Object.entries(zip.files);
        for (let i = 0; i < entries.length; i++) {
            const [name, file] = entries[i];
            if (file.dir) {
                continue;
            }
            files.set(name, await file.async("arraybuffer"));
        }

        cached_default_skin_files = files;
        loading_default_skin_files = null;
        return files;
    })();

    return loading_default_skin_files;
};
`;

    await writeFile(embedded_module_path, module, "utf8");
    console.log(`[generate:skin] wrote embedded module to ${embedded_module_path}`);
};

await main();
